### ISSUE TITLE
Ошибка загрузки 3Д модели в стейдже

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/dream-team#108]
### Описание бага

Приложение падает при переходе на индексную страницу в стейдже с 3Д моделью.

Какие были попытки:
- прямой импорт в TS ассетов
- использование стандартного `asset/resource` вебпака
- использование доп. `Suspense` и динамический импорт модели в компонент

### Воспроизведение

1. https://stage.dream-team.tech

### Ожидаемое поведение

Страница загрузилась, 3Д модель отрендерилась.

### Материалы

Safari:

```
Could not load /_next/static/media/sphere.gltf: Length out of range of buffer
```

Chrome:

```
Could not load /_next/static/media/sphere.gltf: Invalid typed array length: 300
```

### Данные окружения

Chrome: 120.0.6099.234 
Safari: 17.2.1 (18617.1.17.11.12, 18617)

**Comment by TorinAsakura** [comment]
Вообще очень похоже на проблемы со стороны инфры, но, никак не кода

**Comment by Nelfimov** [comment]
Ошибка была связана с большим размером `sphere-data.bin`. Решили перемещением модели в CDN.
