### ISSUE TITLE
Оптимизация загрузки 3Д модели

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/dream-team#112]
### С чем связан запрос на фичу?

Сейчас 3Д модель весит ~300Мб, из-за чего загрузка модели в среднем 20 секунд на хорошем интернете. Необходимо снизить это время.

### Расскажите как вы это себе видите

Стейдж находится по адресу: https://stage.dream-team.tech

Можно попробовать несколько методов:

### Адаптивная загрузка

Адаптивная загрузка позволяет использовать несколько версий модели в зависимости от железки. 

Например, для пользователей с мобильных устройств или медленного интернета можно загружать модель с меньшим количеством полигонов или более низким разрешением текстур

### Обработка на серверсайд

Саме жрущие операции выносим на сервер до того, как 3D-модель будет отправлена клиенту. Соответственно, клиенты будут получать уже оптимизированные версии модели

### Прогрессивная загрузка

Или, как я её называю - партиционная загрузка. Я знаю пару способов, но, могут быть и другие:

- LOD (Level of Detail): Создайте несколько версий модели с разной степенью детализации
- Streaming: использовать потоковую передачу для постепенной загрузки модели

**Comment by Amiditin** [comment]
@Nelfimov 

> Например, для пользователей с мобильных устройств или медленного интернета можно загружать модель с меньшим количеством полигонов или более низким разрешением текстур

Лоуполигональную модель как-то проверял, она полностью размытая была, а разница в размере была только в 2 раза. (300mb основная, 150mb лоу)

> Прогрессивная загрузка
 
Почти весь вес модели это её анимации, без них она весит около 3mb. Как вариант можно загрузить сначала её, а после заменить на модель с анимациями, на видео скорось интернета 200 Mbit/s:

<details>

[Запись экрана от 30.01.2024 20:28:51.webm](https://github.com/torin-asakura/dream-team/assets/80476878/e730cab2-2667-4fca-a80d-00459cf6a5be)


</details>

**Comment by TorinAsakura** [comment]
> @Nelfimov
> 
> > Например, для пользователей с мобильных устройств или медленного интернета можно загружать модель с меньшим количеством полигонов или более низким разрешением текстур
> 
> Лоуполигональную модель как-то проверял, она полностью размытая была, а разница в размере была только в 2 раза. (300mb основная, 150mb лоу)
> 
> > Прогрессивная загрузка
> 
> Почти весь вес модели это её анимации, без них она весит около 3mb. Как вариант можно загрузить сначала её, а после заменить на модель с анимациями, на видео скорось интернета 200 Mbit/s:
> 
>  30.01.2024.20.28.51.webm

если наша проблема это анимция, то тут видимо только через canvas/webgl решать эту задачу

**Comment by Nelfimov** [comment]
Решено через размещение модели в СDN
