### ISSUE TITLE
Разместить в стейдже обе 3Д модели

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/dream-team#113]
### Какого рода задача?

Необходимо разместить в стейдже обе 3Д модели - новую и предыдущую версию для наглядного сравнения качества.

### Что и где будем менять?

- [ ] отыскать первую версию модели
- [ ] передать девопсу на размещение в CDN
- [ ] ссылку на CDN в код
- [ ] старую модель разместить слева от новой:

![image](https://github.com/torin-asakura/dream-team/assets/44067768/c2a8e463-42af-45f2-8fe7-7eb41f4e0824)

- [ ] дополнительно: попробовать перевести стейдж [на ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration)

**Comment by Amiditin** [comment]
> отыскать первую версию модели

@Nelfimov самая первая модель в этом [комите](https://github.com/torin-asakura/dream-team/pull/103/commits/f6141b6c1fa838962c24f74297271867acf0026c), а последние, уже пофикшеные, сжатые, лоуполигональные [здесь](https://github.com/torin-asakura/dream-team/tree/f6faaa511af07bedce4ee4e0336f61ffb8ceff16/3D).

**Comment by Nelfimov** [comment]
@Amiditin берем отсюда

https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847

**Comment by Amiditin** [comment]
> @Amiditin берем отсюда
> 
> [#37 (comment)](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847)

Там у моделей не glb/gltf формат, не могу их взять

**Comment by Nelfimov** [comment]
Другие лоадеры/хуки не подойдут?

**Comment by TorinAsakura** [comment]
> > @Amiditin берем отсюда
> > [#37 (comment)](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847)
> 
> Там у моделей не glb/gltf формат, не могу их взять

что значит не можешь? код потерял? в реакте забанен?

**Comment by Amiditin** [comment]
> Другие лоадеры/хуки не подойдут?

у [react-three/drei](https://www.npmjs.com/package/@react-three/drei) только такие лоадеры есть:

[useGLTF](https://www.npmjs.com/package/@react-three/drei#usegltf)
[useFBX](https://www.npmjs.com/package/@react-three/drei#usefbx)
[useTexture](https://www.npmjs.com/package/@react-three/drei#usetexture)
[useKTX2](https://www.npmjs.com/package/@react-three/drei#usektx2)
[useCubeTexture](https://www.npmjs.com/package/@react-three/drei#usecubetexture)
[useVideoTexture](https://www.npmjs.com/package/@react-three/drei#usevideotexture)
[useTrailTexture](https://www.npmjs.com/package/@react-three/drei#usetrailtexture)
[useFont](https://www.npmjs.com/package/@react-three/drei#usefont)
[useSpriteLoader](https://www.npmjs.com/package/@react-three/drei#usespriteloader)

Из них использовал только `useGLTF` `useFBX`

**Comment by Amiditin** [comment]
могу так попробовать https://stackoverflow.com/questions/76775637/loading-obj-with-react-and-three-js

**Comment by TorinAsakura** [comment]
> могу так попробовать https://stackoverflow.com/questions/76775637/loading-obj-with-react-and-three-js

слушай, у тебя даже код сохранился в старых коммитах, сделай также, в чём проблемы-то?

**Comment by Amiditin** [comment]
> могу так попробовать https://stackoverflow.com/questions/76775637/loading-obj-with-react-and-three-js

Моделька не отображается этим методом, сейчас пробую её сконвертить в glb.

> слушай, у тебя даже код сохранился в старых коммитах, сделай также, в чём проблемы-то?

[здесь](https://github.com/torin-asakura/dream-team/commits/master/landing/fragments/landing-hero/src/landing-hero.component.tsx) в истории только два комита, а в PR прикрепленных к старым таскам вижу только что видео заменяется на картинку

**Comment by TorinAsakura** [comment]
> > могу так попробовать https://stackoverflow.com/questions/76775637/loading-obj-with-react-and-three-js
> 
> Моделька не отображается этим методом, сейчас пробую её сконвертить в glb.
> 
> > слушай, у тебя даже код сохранился в старых коммитах, сделай также, в чём проблемы-то?
> 
> [здесь](https://github.com/torin-asakura/dream-team/commits/master/landing/fragments/landing-hero/src/landing-hero.component.tsx) в истории только два комита, а в PR прикрепленных к старым таскам вижу только что видео заменяется на картинку

Отдай модельку Кате если до всех пор ничего не получилось, дай ей таску, пускай просто с модельки снимет состояния да пофиксит текущую

**Comment by Amiditin** [comment]
> Отдай модельку Кате если до всех пор ничего не получилось, дай ей таску, пускай просто с модельки снимет состояния да пофиксит текущую

Получилось добавить модель из комента, но она без тектстур и анимаций, поэтому с текущим нашим освещением выглядит так 
![image](https://github.com/torin-asakura/dream-team/assets/80476878/ee351c5d-7ed6-4c83-8d47-87e2e31bf2f2)

**Comment by Nelfimov** [comment]
https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1073736244

Необходимо рядом с нашей моделью добавить видео из кода этого коммента, т.е. откатится на состояние кода в тот момент, вытащить видео и добавить в текущий стейдж, так же слева от новой модели.

Это нужно чтобы диз мог сравнить и доработать модель.

**Comment by Amiditin** [comment]
@Nelfimov ветка [feat/comparison-3d-models](https://github.com/torin-asakura/dream-team/tree/feat/comparison-3d-models), добавил видео:

<details>

[Запись экрана от 01.02.2024 13:59:37.webm](https://github.com/torin-asakura/dream-team/assets/80476878/10adb42f-a5a3-4bb9-8968-04b09a37a9ce)
</details>

**Comment by Nelfimov** [comment]
на ревью и отправляем в стейдж
