### ISSUE TITLE
Ошибка загрузки в стейдже

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/dream-team#116]
### Описание бага

Ошибка клиента - невозможно получить ассет новой модели. Необходимо перенести ассеты в CDN.

### Воспроизведение

1. https://stage.dream-team.tech

### Ожидаемое поведение

Сайт открывается, модель и видео рендерятся

### Материалы

![image](https://github.com/torin-asakura/dream-team/assets/44067768/99f2b1e6-2217-42e2-8347-4025154686a8)

### Данные окружения

- macOS 13.6.4
- Safari 17.3

**Comment by Amiditin** [comment]
@Nelfimov файлы `sphere-no-animation` [тут](https://github.com/torin-asakura/dream-team/tree/7bb43574dea4d6ac380f9f9eec867cf5108d4e24/ui/sphere/assets), в cdn не знаю как добавить

**Comment by Nelfimov** [comment]
Кидай их девопсу конечно же

**Comment by Amiditin** [comment]
> файлы `sphere-no-animation` [тут](https://github.com/torin-asakura/dream-team/tree/7bb43574dea4d6ac380f9f9eec867cf5108d4e24/ui/sphere/assets)

@eantdz ^
