### ISSUE TITLE
Изменение glb 3D сферы

### ISSUE THREAD

**Issue by pussypistolss** [torin-asakura/dream-team#118]
### Какого рода задача?

Необходимо изменить анимацию и уменьшить размер glb файла.

### Что и где будем менять?

Нужно снять состояние с [изначальной 3d модели obj формата](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847), изменить [нынешнюю glb 3d модель](https://github.com/torin-asakura/dream-team/pull/103), и по возможности уменьшить размер файла.

![image](https://github.com/torin-asakura/dream-team/assets/147274591/161eb186-c2d5-4e2f-93c7-1b123f375e96)

### Укажите референс

https://github.com/torin-asakura/dream-team/issues/113

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/7a83ab17-81c9-40bd-b21e-526e7a5ef7a3

вес 375 мб

**Comment by TorinAsakura** [comment]
> IMG_8206.MP4 
> 
> вес 375 мб

обрати внимания на рёбра - они у тебя уже и тайминги отличаются

**Comment by pussypistolss** [comment]
> обрати внимания на рёбра - они у тебя уже и тайминги отличаются

Исправила,


https://github.com/torin-asakura/dream-team/assets/147274591/1f84f46e-4c27-4be5-8bd7-f852a7aed986


Повторить анимацию в конце не получается, постаралась сделать просто похоже

**Comment by TorinAsakura** [comment]
> > обрати внимания на рёбра - они у тебя уже и тайминги отличаются
> 
> Исправила,
> 
>  IMG_8224.MP4 
> 
> Повторить анимацию в конце не получается, постаралась сделать просто похоже

что у тебя происходит на 0:08? Какой-то секундный крен (поворот)

**Comment by pussypistolss** [comment]
> что у тебя происходит на 0:08? Какой-то секундный крен (поворот)



https://github.com/torin-asakura/dream-team/assets/147274591/e662f663-6b46-456b-a9cf-42900dd6ac4d

Убрала его

**Comment by TorinAsakura** [comment]
@pussypistolss 

Давай распишем состояния. Я вижу, что ты не понимаешь что происходит со сферой. Распиши потаймингово её состояния вида:
- 00:00 - 00:03 - раскрытие из оси Y в ось X

**Comment by pussypistolss** [comment]
@TorinAsakura 
Грани сферы:
- 00:00 - 00:03 - раскрытие граней сферы.
- 00:03 -00:05  - собранное состояние граней
- 00:05-00:09 - расширение граней
- 00:09-00:10 - закрытие граней сферы

Турбулентность:

- 00:00-00:01 - минимальная турбулентность
- 00:01-00:02 - увеличение турбулентности
- 00:02-00:03 - уменьшение турбулентности
- 00:03-00:05 - значение турбулентности не меняется
- 00:05-00:10 - увеличение турбулентности

Положение:

- 00:00-00:05 - поворот по диагонали из Y оси  в X ось
- 00:05-00:10 - поворот по диагонали из X оси  в Y ось

Так?

**Comment by TorinAsakura** [comment]
> @TorinAsakura Грани сферы:
> 
> * 00:00 - 00:03 - раскрытие граней сферы.
> * 00:03 -00:05  - собранное состояние граней
> * 00:05-00:09 - расширение граней
> * 00:09-00:10 - закрытие граней сферы
> 
> Турбулентность:
> 
> * 00:00-00:01 - минимальная турбулентность
> * 00:01-00:02 - увеличение турбулентности
> * 00:02-00:03 - уменьшение турбулентности
> * 00:03-00:05 - значение турбулентности не меняется
> * 00:05-00:10 - увеличение турбулентности
> 
> Положение:
> 
> * 00:00-00:05 - поворот по диагонали из Y оси  в X ось
> * 00:05-00:10 - поворот по диагонали из X оси  в Y ось
> 
> Так?

это ты описала свою сферу, а я прошу расписать по оригинальной, ведь, если ты сделешь раскадровку или просто замедлишь анимацию, ты увидишь отличия в поведении, они, как тебе могут показать незначительными, но, именно эти мелочи создают эту композицию

**Comment by jade-smith-rs46** [comment]
> > это ты описала свою сферу,
> 
> Нет, я описала сейчас оригинальную сферу. Вот эту.
> 
>  2ee21dfa-sphere-with-bg.webm 
> 
> Я поняла что сфера, которую я делаю поворачивается не по таймингам. Сейчас буду переделывать.

окей, теперь давай сравним с нашей

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/1fb87d17-c92f-4bbe-8ef9-17712b007fad

@TorinAsakura

**Comment by TorinAsakura** [comment]
> IMG_8241.MP4 
> 
> @TorinAsakura

снова у тебя крены между переходами, буквально секундный, ты не видишь их?

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/ac1bb7b6-6833-4605-b842-bdfe69aca75e

@TorinAsakura
