### ISSUE TITLE
Заменить 3D сферу на новую

### ISSUE THREAD

**Issue by Amiditin** [torin-asakura/dream-team#120]
### С чем связан запрос на фичу?

Необходимо заменить сферу на новую #119

### Расскажите как вы это себе видите

- [x] Сконвертировать новую сферу в jsx
- [x] Выгрузить в CDN модель новой сферы с анимациями и без анимаций

**Comment by Amiditin** [comment]
@eantdz заменил модельки сферы в этой [ветке](https://github.com/torin-asakura/dream-team/tree/c28c027d9c03d712c8b704a404f09b6f9da28cde/ui/sphere/assets), нужно выгрузить в cdn

**Comment by eantdz** [comment]
> @eantdz заменил модельки сферы в этой [ветке](https://github.com/torin-asakura/dream-team/tree/c28c027d9c03d712c8b704a404f09b6f9da28cde/ui/sphere/assets), нужно выгрузить в cdn

@Amiditin заменил в cdn

**Comment by Amiditin** [comment]
> > @eantdz заменил модельки сферы в этой [ветке](https://github.com/torin-asakura/dream-team/tree/c28c027d9c03d712c8b704a404f09b6f9da28cde/ui/sphere/assets), нужно выгрузить в cdn
> 
> @Amiditin заменил в cdn

@eantdz всё ещё старые приходят:
<details>

[Запись экрана от 13.02.2024 00:23:18.webm](https://github.com/torin-asakura/dream-team/assets/80476878/bb648859-d6e0-40a3-8eba-f7306330a1cd)

</details>

**Comment by Amiditin** [comment]
> Отключил кеширование на стороне CDN, если не поможет через несколько часов - думаю нужно пробовать тригерить релиз, возможно новый образ поможет. @Amiditin

@eantdz помогло, приходят новые

@pussypistolss освещение будем менять?

<details>

![image](https://github.com/torin-asakura/dream-team/assets/80476878/db8db612-1a0c-44a2-883c-fd01fc1bc140)

</details>

**Comment by pussypistolss** [comment]
> @pussypistolss освещение будем менять?
> 
Будем,вечером созвонимся

**Comment by Amiditin** [comment]
@eantdz ещё раз обновили модельки сферы [файлы](https://github.com/torin-asakura/dream-team/tree/refactor/sphere-model/ui/sphere/assets), нужно заменить в cdn

**Comment by eantdz** [comment]
> @eantdz ещё раз обновили модельки сферы [файлы](https://github.com/torin-asakura/dream-team/tree/refactor/sphere-model/ui/sphere/assets), нужно заменить в cdn

@Amiditin заменил

**Comment by Nelfimov** [comment]
@Amiditin необходимо вернуться к этому вопросу - либо добить анимацию либо добавить видео.

**Comment by Amiditin** [comment]
@eantdz можешь выгрузить эти [видео](https://github.com/torin-asakura/dream-team/tree/c5b5ce743ab53f008ae887112bf7a3aef1e4f552/ui/sphere/src/video) в cdn

**Comment by Amiditin** [comment]
@Nelfimov нашел способ получать цвет бэкграунда у видео, в Chrome и FireFox работает, можешь ещё посмотреть как будет выглядеть в Safari?

<details>
<summary>Цвета до и после:</summary>

- Chrome бэк видео rgb(55,57,107) -> получаемый цвет rgb(55,57,107)
- FireFox бэк видео rgb(56,54,105) -> получаемый цвет rgb(56,54,105)

[Запись экрана от 19.04.2024 03:09:33.webm](https://github.com/torin-asakura/dream-team/assets/80476878/30e2ba2c-2698-42d2-9dde-5f9ada604961)

</details>

<details>
<summary>Загрузка приложения</summary>

[Запись экрана от 19.04.2024 03:18:23.webm](https://github.com/torin-asakura/dream-team/assets/80476878/64512090-3423-4806-a441-7970d266b033)

</details>

**Comment by eantdz** [comment]
> @eantdz можешь выгрузить эти [видео](https://github.com/torin-asakura/dream-team/tree/c5b5ce743ab53f008ae887112bf7a3aef1e4f552/ui/sphere/src/video) в cdn

@Amiditin готово

**Comment by Nelfimov** [comment]
@Amiditin на ветке в сабже:

<details>

<img width="1335" alt="Screenshot 2024-04-19 at 13 21 44" src="https://github.com/torin-asakura/dream-team/assets/44067768/002bdf81-b29b-4b6d-afe4-a21b985520bc">

<img width="1366" alt="image" src="https://github.com/torin-asakura/dream-team/assets/44067768/dabe8ef7-2534-47b2-a4ab-38df83404653">

</details>

**Comment by Amiditin** [comment]
> @Amiditin на ветке в сабже:

@Nelfimov непонятно почему просчитывает цвет как черный даже в хроме, если бы цвет не просчитывался прокидывался бы дефолтный: 
https://github.com/torin-asakura/dream-team/blob/3ec8ded2a0edbc2a0b166589f57f7c0572b94d20/landing/fragments/landing-hero/src/landing-hero.component.tsx#L46

Добавил комит на игнор черного цвета, можешь ещё раз посмотреть?

**Comment by Nelfimov** [comment]
<details>

![image](https://github.com/torin-asakura/dream-team/assets/44067768/726c18fb-caef-4189-89c9-8fc4b20850f6)


# Обыная перезагрузка:

![Screenshot 2024-04-19 at 14 22 11](https://github.com/torin-asakura/dream-team/assets/44067768/18a52341-c6da-401e-ba32-cf143c8c354d)

![Screenshot 2024-04-19 at 14 21 27](https://github.com/torin-asakura/dream-team/assets/44067768/cdf73f56-eefc-42dd-bec1-84df7030b56a)


# Перезагрузка без кэша

![Screenshot 2024-04-19 at 14 21 55](https://github.com/torin-asakura/dream-team/assets/44067768/4dc76337-edd5-44b7-b5a8-cbda4682de3b)

</details>

**Comment by Nelfimov** [comment]
На safari сайт зависает при первой загрузке. Связано с реализацией подстройки фона под преобладающий цвет видео:

https://github.com/torin-asakura/dream-team/blob/34ad8262a034edd93b0e061aae3efdcbb11642ff/landing/fragments/landing-hero/src/landing-hero.component.tsx#L37

В хроме такое не воспроизводится.

Из мастера сейчас улетает в стейдж: https://stage.dream-team.tech

**Comment by Nelfimov** [comment]
https://github.com/torin-asakura/dream-team/assets/44067768/bca9d993-b0a8-423b-bc6a-d5615a2d950d

**Comment by oksssvv** [comment]
@Nelfimov 

а есть вариант это дело по другому написать?

я реализовала другой способ, через userAgent узнаем сафари ли это, если да возвращаем один цвет, если нет то другой

хром:
![Снимок экрана от 2024-06-10 19-53-46](https://github.com/torin-asakura/dream-team/assets/126156026/746e0e69-78f5-4af0-80ac-fcf76e86fed8)

сафари:
![Снимок экрана от 2024-06-10 19-52-43](https://github.com/torin-asakura/dream-team/assets/126156026/5c6f471b-8b12-4dc0-8202-7d86df6107a7)

**Comment by Nelfimov** [comment]
Хорошее решение. Попробуй еще firefox и какой нибудь яндекс браузер. Если пройдет - выпускаем в стейдж и я протестирую наживую.

**Comment by oksssvv** [comment]
@Nelfimov 
уже протестила допольнительно yandex, opera, mozilla
для мозилы другой цвет нужен, добавила, протестила еще раз, все ок

вот хук:

```typescript
const useHeroBackgroundColor = () => {
  const [color, setColor] = useState('background.hero')

  useEffect(() => {
    const userAgent = navigator.userAgent.toLowerCase()
    if (userAgent.indexOf(Browser.CHROME) > -1) {
      setColor('background.purpleInChrome')
    } else if (userAgent.indexOf(Browser.SAFARI) > -1) {
      setColor('background.purpleInSafari')
    } else if (userAgent.indexOf(Browser.FIREFOX) > -1) {
      setColor('background.purpleInFirefox')
    } else {
      setColor('background.hero')
    }
  }, [])

  return { heroBackgroundColor:color }
}
```

оставляем?

**Comment by Nelfimov** [comment]
Через свитч это никак не отрефакторить?

**Comment by oksssvv** [comment]
@Nelfimov 
больше кода получится, в итоге придется использовать и if и switch или 2 свича, тот способ, что я описала выше - компактнее
