### ISSUE TITLE
Получение цвета фона видео-сферы

### ISSUE THREAD

**Issue by oksssvv** [torin-asakura/dream-team#130]
### Описание бага

- [ ] исправить некорректное отображение цвета фона / `main/hero`
- [ ] избавиться от ошибки CORS / `main/hero`

**Comment by Nelfimov** [comment]
![image](https://github.com/torin-asakura/dream-team/assets/44067768/0328d013-d6e5-4665-a8e6-a4dfcb9c4224)

**Comment by oksssvv** [comment]
@Nelfimov 
а на хроме получается и цвет есть и ошибок корса нет, так?

**Comment by Nelfimov** [comment]
![image](https://github.com/torin-asakura/dream-team/assets/44067768/123df59f-55f4-48c3-a013-d15f282ffb42)

**Comment by oksssvv** [comment]
@Nelfimov 

а на предыдущей версии этого getColor не было ошибок CORS? (когда Дима сделал этот функционал)

**Comment by Nelfimov** [comment]
Ошибок не было.

**Comment by oksssvv** [comment]
@Nelfimov 
я вернулась к состоянию кода который был изначально, лишь исправила несколько мапов (не хватало атрибутов `key`)

я, к сожалению не могу воспроизвести твою проблему, т.к. у меня нет такого окружения, линуксовый вебкит ведет себя также как Хром (без каких либо фризов)

могу ли попросить тебя лично попытаться локализовать проблему с фризами используя Safari, и возможно исправить ситуацию

если все таки фризы связаны с getColor и их не получится устранить - то выходом из ситуации, без подобных костылей, вижу:
- получить исходник сферы(.blend) и убрать в нем фон (на сайтах по удалению или плохо вырезают сферу или же конвертируют в гиф)
- разместить сферу без фона и понаблюдать как это дело выглядит на сайте (нормально ли отрабатывает прозрачность)

^ в таком случае не придется прибегать к подставке фона под видео и не будет таких ресурсозатратных способов решения проблемы

вопрос: 
сможешь помочь? не получается работать в слепую в рамках этой задачи

**Comment by Nelfimov** [comment]
Не увидел изменения в метод получения цвета, локально по прежнему черный 

<img width="1387" alt="image" src="https://github.com/torin-asakura/dream-team/assets/44067768/256b806c-5416-4766-a2f1-e57f7e78af9a">

Касательно фризов - они были из-за интервального опроса внутри `useEffect`. Для эксперимента - сделай задержку перед "взятием" цвета, скажем секунд на 10 - тогда мы  увидим после загрузки страницы сначала черный фон, а затем "что-то"

**Comment by oksssvv** [comment]
@Nelfimov 
ветка была в состоянии изменений которые делал еще Дима

тут проблема в том что Сафари не запускает видео для лучшего пользовательского опыта, даже если есть атрибут autoPlay 

цвет из видео получается только если видео воспроизводится, т.е. пока видео в начальном состоянии стопа - цвет вычисляться не будет и будет или черный или начальный фиолетовый (в сафари отображающийся не под цвет видео)

в общем установила задержку на 10 сек, ветка актуальная, можешь пожалуйста проверить как теперь (у меня все также браузеры без проблем обрабатывают)

**Comment by Nelfimov** [comment]
![Screenshot 2024-06-17 at 13 22 45](https://github.com/torin-asakura/dream-team/assets/44067768/0ea4c3d3-1998-49d2-8f5c-ac2a7fd224aa)
![Screenshot 2024-06-17 at 13 22 47](https://github.com/torin-asakura/dream-team/assets/44067768/da3d463a-f64f-4e46-acbb-3e03ad803219)

**Comment by oksssvv** [comment]
@Nelfimov 
1 скрин я так понимаю это сафари, был подставлен дефолтный фон, и он не меняется т.к. видео не воспроизводится автоматически (из-за политики браузера)

если ты в ручную его запустишь - то фон подставится

вопрос:
как можно выйти из ситуации? у меня вариантов больше нет
кроме как для webkit-a оставить постер со сферой а для гугла воспроизводить видео

**Comment by Nelfimov** [comment]
> если ты в ручную его запустишь - то фон подставится

Видео запускается автоматически. Скрин выслал тебе в конце видео.

> как можно выйти из ситуации? у меня вариантов больше нет
> кроме как для webkit-a оставить постер со сферой а для гугла воспроизводить видео (как временное решение для нормального вида на проде)

Для быстрого фикса прода - поставь цвет который хром выдает.

Для правильного фикса - если считаешь что теория с автовоспроизведением верна - поищи эвент хэндлер для старта видео. После старта - бери цвет. Так же попробуй отрубить экран загрузки чтобы сразу открывалось видео.

Либо копай ишью у библиотеки которую используем.

**Comment by oksssvv** [comment]
@Nelfimov 

можешь пожалуйста обновить ветку и проверить нынешнее состояние, запушила коммит

как гугл и сафари отображает 

(установила цвет который у тебя был на скрине как изначальный в видео, т.к. гугл отрабатывает подстановку нормально, возможно сработает)
