### ISSUE TITLE
Buglist

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dream-team#14]
- [x] не является SPA
- [x] нет SEO каркаса (тайтл, дескрипшн, опенграф, имейдж превью, фавикон)
- [x] в футере отсутствуют ссылки
- [x] [a] использует дефолтные пропсы браузера, по крайней мере в футере
- [x] поповер должен быть соразмерен контенту (@dakand)
- [x] RadioButton-stateless
- [x] дублируются скиллы, в Data Science непонятный ident во второй строке и он дублируется с AI, вычисти это дело, пускай девчонки наполняют
- [x] carousel-item_Body нет отступа между контентом и ссылкой
- [x] отображение переключения языка перепутано
- [x] в РУ версии нет лого в футере
- [x] У карусели сломаны слайдеры
- [x] Внутри поповера отзыва ломается состояние слайдера
- [x] У текст линков (например privacy policy) нет стейта
- [x] У инпута есть мертвая зона при попытке фокуса
- [x] У формы разные размеры при переключении языков
- [x] Текст у privacy-policy не центрирован в английской версии
- [x] Фикс фона для блока с видео (@dakand)
- [x] Убрать бабл у кнопки copy to clipboard 
- [x] Скиллы в поповере
- [x] Сменить шрифт Gordita -> Inter
- [x] Закрытие поповера на Esc
- [x] Title не подтягивается от wordpress
- [x] Страницы не засинканы с вп
- [x] Заменить видео в хиро - добавить анимацию отдельно от фона.
- [x] Кнопка смены языка немного вытянута в ширину. Сделать круглой.
- [x] В блоке "сроки" изображение визуально очень близко к тексту. Скорее всего из-за того,что из фигмы экспортнул не тот слой. Нужно Image 3, а не Image 3 (internal) https://yadi.sk/i/CIzumbuh6_aVFA
- [x] В карточке отзыва у текста отзыва lh:normal. Нужно 1.75.
- [x] В карточке отзыва нужно ограничить текст четырьмя строчками.
- [x] В карточке отзыва между кнопкой "Подробнее" и текстом нужен отступ такой же, как между текстом и заголовком внутри карточки.
- [x] В карточке отзыва "+" добавлен символом, а не иконкой. 
- [x] На странице контактов мета должен быть апперкейсом.
- [x] У кнопки "Скопировать" в дизайне появилось состояние success. 
- [x] У инпута отступы слева-справа 20px. Из-за скругления границ горизонтальные отступы должны быть больше, чем вертикальные.
- [x] Нет кнопки закрытия (крестик) в правом верхнем углу при открытой модалке.
- [x] Пофиксить basePath в теме (next.config.js)

**Comment by TFK70** [comment]
> не является SPA

https://github.com/torin-asakura/dream-team/issues/8

**Comment by TFK70** [comment]
> поповер должен быть соразмерен контенту (@dakand)

@dakand посмотри пожалуйста

**Comment by dakand** [comment]
@TFK70 сделал, коммент в фигме оставил на ключевой точке

**Comment by TFK70** [comment]
@dakand у видео нет прозрачного бекграунда:

![image](https://user-images.githubusercontent.com/62806448/134822372-cc2b21f4-3e63-4529-89aa-ff5a91239bd8.png)
