### ISSUE TITLE
Видео в Hero

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/dream-team#37]
### Проблема

На разных платформах/браузерах фон видео в hero не совпадает с фоном самого блока hero

### Материалы

![image](https://user-images.githubusercontent.com/62806448/159235435-805abab4-0a88-4101-b4a7-bfa39b7dbae9.png)

**Comment by TFK70** [comment]
@dakand проблема в кроссбраузерности, на одной платформе видео в сафари и хроме рендерится по-разному:

https://user-images.githubusercontent.com/62806448/159239989-d23a0383-e568-4a4f-b062-1bdefdd60268.mov

Немного погуглил - наткнулся на наиболее подробную [статью](https://dallas-reedy.medium.com/how-to-solve-video-color-inconsistencies-across-browsers-a35efeb95196) по этой проблеме где в конечном итоге предлагали рендерить видео через канвас (и затронули тему color profiles). Попробовал - результат чуть лучше, но все-равно не помогло:

https://user-images.githubusercontent.com/62806448/159244398-0753806a-d39c-4bb5-a564-879cd5e1a18e.mov

**Comment by dakand** [comment]
@TFK70 https://disk.yandex.ru/d/cOz4ErDt4Q7rMw

**Comment by TFK70** [comment]
@dakand привет, есть несколько вопросов насчет ассетов по шарику [отсюда](https://github.com/torin-asakura/dream-team/issues/37#issuecomment-1074831847)

1. Есть ли  в `.obj` данные об анимации сферы или там только описание ее шейпов (статика)?
2. В дополнение к первому пункту: я нигде не нашел примеров загрузки анимированных `.obj` моделей, но нашел пример с `.glb` - [клик](https://codesandbox.io/s/react-three-fiber-importing-scenes-with-actions-from-blender-forked-yjdv5l?file=/src/Sphere.js). Ниже экскурс по сендбоксу распишу

<details>

**Экскурс**

- В левом сайдбаре можно увидеть все файлы. В директории `public` лежат как раз `.glb` файлы которые рендерит `@react-three/fiber`
- Сендбокс поначалу не будет показывать содержимое файлов и напишет `The file is not displayed in the editor because it is either binary or uses an unsupported text encoding.Do you want to open it anyway?`. Последнее предложение кликабельное, если на него нажать - можно будет увидеть содержимое
- В примере моделей больше одной, там еще есть пример со сферой. Чтобы его посмотреть в файле `App.js` нужно заменить 3 строку с `import Kick from "./Kick.js";` на `import Kick from "./Sphere.js";` и нажать  `cmd+s`

</details>

Ии соответственно предлагаю экспортировать сферу в `.gld` если это возможно

К слову, вот пример рендера `.obj` + `.mtl` - [click](https://codesandbox.io/s/objloader-51zks?file=/src/index.js)

**Comment by dakand** [comment]
react-three-fiber

---

### URL
https://prod.spline.design/kV17TlAArZunhD1a/scene.splinecode

---

### Code:

/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/kV17TlAArZunhD1a/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#676aaa']} />
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={1.85}
          far={100000}
          near={-100000}
          position={[-3.8, -47.38, 1060.14]}
        />
        <group name="Main" position={[0, 0, 0.97]}>
          <mesh
            name="Sphere 9"
            geometry={nodes['Sphere 9'].geometry}
            material={materials['Sphere 9 Material']}
            receiveShadow
            position={[35.74, 82.57, 63.57]}
            rotation={[2.87, 1.22, 2.73]}
          />
          <mesh
            name="Sphere 8"
            geometry={nodes['Sphere 8'].geometry}
            material={materials['Sphere 8 Material']}
            receiveShadow
            position={[-55.07, 69.95, 30.72]}
            rotation={[0.06, 0.45, -0.65]}
          />
          <mesh
            name="Sphere 7"
            geometry={nodes['Sphere 7'].geometry}
            material={materials['Sphere 7 Material']}
            receiveShadow
            position={[-99.53, 14.11, -17.74]}
            rotation={[0.13, -0.3, -0.24]}
          />
          <mesh
            name="Sphere 6"
            geometry={nodes['Sphere 6'].geometry}
            material={materials['Sphere 6 Material']}
            receiveShadow
            position={[61.55, 69.19, -26.34]}
            rotation={[-0.22, 0.44, 0.49]}
          />
          <mesh
            name="Sphere 5"
            geometry={nodes['Sphere 5'].geometry}
            material={materials['Sphere 5 Material']}
            receiveShadow
            position={[-7.61, -23.03, 80.41]}
            rotation={[0.26, 0, 0]}
          />
          <mesh
            name="Sphere 4"
            geometry={nodes['Sphere 4'].geometry}
            material={materials['Sphere 4 Material']}
            receiveShadow
            position={[36.59, -71.1, 49.58]}
            rotation={[-0.53, -0.33, 0.5]}
          />
          <mesh
            name="Sphere 3"
            geometry={nodes['Sphere 3'].geometry}
            material={materials['Sphere 3 Material']}
            receiveShadow
            position={[76.31, 10.28, 56.61]}
            rotation={[0, -0.68, 0.03]}
          />
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials['Sphere 2 Material']}
            receiveShadow
            position={[-77.28, -36.8, 27.01]}
            rotation={[0.04, 0.45, 0.26]}
          />
          <group name="Orbit  2 (group)" rotation={[-Math.PI / 4, -Math.PI / 4, 0]}>
            <mesh
              name="Orbit 2"
              geometry={nodes['Orbit 2'].geometry}
              material={materials['Orbit 2 Material']}
              receiveShadow
            />
          </group>
          <group name="Orbit  1 (group)" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="Orbit 1"
              geometry={nodes['Orbit 1'].geometry}
              material={materials['Orbit 1 Material']}
              receiveShadow
            />
          </group>
          <mesh
            name="Boolean"
            geometry={nodes.Boolean.geometry}
            material={materials['Boolean Material']}
            castShadow
            receiveShadow
            position={[0, 0, -0.97]}
          >
            <mesh
              name="Helix"
              geometry={nodes.Helix.geometry}
              material={materials['Helix Material']}
              visible={false}
              castShadow
              receiveShadow
              position={[0, -30, 0]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              visible={false}
              castShadow
              receiveShadow
            />
          </mesh>
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={3.1} color="#eaeaea" position={[0, 1, 0]} />
      </group>
    </>
  )
}

**Comment by TFK70** [comment]
https://github.com/torin-asakura/dream-team/pull/63

Анимация была заменена на изображение

**Comment by TorinAsakura** [comment]
Практическое тестирование, тесты Lighthouse для spline:
* Ваш элемент - score 52
* https://prod.spline.design/6PqupwhGDK76msvR/scene.splinecode тупо куб - score 82
* Без spline объекта - score 88
* https://spline.design/ - score 65

Просадка явно из-за объекта, но это нормально т.к. используются прозрачность, линии, градиенты и анимация

**Comment by TFK70** [comment]
@TorinAsakura а что насчет fiber? Его тогда не будем пробовать?

**Comment by YuraBronsky** [comment]
Я так понял надо сделать сферу и эту анимацию в видео?
Прости если я что то не так понял

**Comment by TorinAsakura** [comment]
Да, всё верно. Формат для three.js

**Comment by YuraBronsky** [comment]
Сделал анимацию, добавил превью видео.
Сам проект\модель - https://dropmefiles.com/5DMuE пароль: 7NeP4N
Запустить анимацию в отдельной модели у меня не получилось, хоть и все в верном формате. Я так подозреваю что gltf не поддерживает шейдинговую анимацию. Попробуй пожалуйста,если не заработает, то я попробую это сделать по другому.
https://github.com/torin-asakura/dream-team/assets/69975444/daa79d73-28a4-4da7-bc9f-2197a4d66bfc

**Comment by TorinAsakura** [comment]
> Сделал анимацию, добавил превью видео. Сам проект\модель - https://dropmefiles.com/5DMuE пароль: 7NeP4N Запустить анимацию в отдельной модели у меня не получилось, хоть и все в верном формате. Я так подозреваю что gltf не поддерживает шейдинговую анимацию. Попробуй пожалуйста,если не заработает, то я попробую это сделать по другому.
> 
>  animation.mp4

Надо настраивать git для работы, так дело конечно не пойдёт через файлообменник перекидываться

**Comment by TorinAsakura** [comment]
> Сделал анимацию, добавил превью видео. Сам проект\модель - https://dropmefiles.com/5DMuE пароль: 7NeP4N Запустить анимацию в отдельной модели у меня не получилось, хоть и все в верном формате. Я так подозреваю что gltf не поддерживает шейдинговую анимацию. Попробуй пожалуйста,если не заработает, то я попробую это сделать по другому.
> 
>  animation.mp4

Анимация потрясающая. Вопрос в наличии альфа-канала

**Comment by YuraBronsky** [comment]
Вот нашел где чел создает в коде такую же анимацию,

[Видео](https://www.youtube.com/watch?v=oKbCaj1J6EI)

**Comment by TorinAsakura** [comment]
> Вот нашел где чел создает в коде такую же анимацию,
> 
> [Видео](https://www.youtube.com/watch?v=oKbCaj1J6EI)

Так, окей, допустим, я понял суть, но, с тебя всё равно нужен объект базовый

**Comment by YuraBronsky** [comment]
Отправлю сегодня

**Comment by TorinAsakura** [comment]
> Отправлю сегодня

статус?

**Comment by YuraBronsky** [comment]
Ну запушить я так и не смог же.
Архив скинул сегодня с проектом.

**Comment by TorinAsakura** [comment]
А ты где-то сказал, что это архив с проектом по этой задаче?

**Comment by YuraBronsky** [comment]
Нет, думал это было понятно.
Но это то что я пытался пугнуть в репозиторий -дизайн.

**Comment by TorinAsakura** [comment]
в архиве лежало 3 файла, какие за что отвечают?

**Comment by YuraBronsky** [comment]
- Бленд файл, это проект в блендере
- бленд1 это создаётся вместе с проектом
- глб, это сфера в формате для gltf

**Comment by TorinAsakura** [comment]
Продолжение в https://github.com/torin-asakura/dream-team/issues/101

**Comment by pussypistolss** [comment]
сделала три анимации.
одна сделана через геометрические ноды, как делал Юра, вторую через изменения текстуры, третью через модификаторы.
Но суть одна что ничего из этого нельзя нормально экспортировать как gltf файл.
gltf не поддерживает ничего из вышеперечисленного. Я сделала только просто шар с крутящимся вокруг него элементом в gltf формате.
Просмотрев кучу инфы на форумах нашла только одно решение этой проблемы - вручную переносить UV карты с моей сеткой покадрово, но я тоже не уверена что это поможет.
Завтра попробую это. Прикрепляю варианты анимации без полного рендера:

Это анимация как Юры, достаточно красивая, но до рендера здесь нельзя увидеть глубину на объекте:

https://github.com/torin-asakura/dream-team/assets/147274591/142cc203-cdca-43e6-988b-1da87209164b

Анимация с помощью изменения текстур:

https://github.com/torin-asakura/dream-team/assets/147274591/237fd910-26a4-4532-af3e-8359c919393b

И последняя анимация, единственная которую получилось экспортировать в gltf

https://github.com/torin-asakura/dream-team/assets/147274591/8f047da2-85eb-4801-9e04-b3211d194006

**Comment by TorinAsakura** [comment]
возвращаемся к работе с анимацией

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/3b632a7d-390c-4e25-8cbe-0a7f7b93d347

Сделала вот такую анимацию в gltf формате,(нужно было еще чуть чуть покопаться что бы экспортировать сферу в этот формат) все отлично открывается, единственное что, если ее в сайт встраивать то стык нужно назад повернуть, что бы было красивее.
Анимация устраивает? Отпиши, какие правки нужно сделать.

**Comment by TorinAsakura** [comment]
> IMG_7064.MP4 
> 
> Сделала вот такую анимацию в gltf формате,(нужно было еще чуть чуть покопаться что бы экспортировать сферу в этот формат) все отлично открывается, единственное что, если ее в сайт встраивать то стык нужно назад повернуть, что бы было красивее. Можно постараться сделать ее более шарообразной, еще поэкспериментировать, что бы результат был лучше. Сферу делала через модификаторы

Отлично, а говоришь нельзя. Да, теперь нужно initial state доработать до полного шарика

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/0e9ecb58-6b08-4560-a96b-75ddb41ab621

что-то такое получилосось

**Comment by TorinAsakura** [comment]
> Sphere111.MP4 
> 
> что-то такое получилось

я понял что ты делаешь, но, это не морфизм, а нам нужен именно морфизмы, когда у тебя происходит деформация объекта, а тут у тебя просто просходит работа с координатой в пространстве, то есть шарик, а на нём страйпы и просто прокручивание в пространстве - это не тот подход

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/7fc34e86-1c86-4458-96f0-e93396f8523c

Вот так?
Скидывать файлик?

**Comment by TorinAsakura** [comment]
> IMG_7077.MP4 
> 
> Вот так? Можно настроить освещение, что бы было контрастнее. Скидывать файлик?

да детка! только немного угол пофикси, посмотри на видео старое и цвет

**Comment by pussypistolss** [comment]
https://github.com/torin-asakura/dream-team/assets/147274591/1bedca76-f78e-4eda-9992-4fadc39ebd43
добавила источники света,
их снова не получается экспортировать в формат gltf. вообще их всего 3 и их можно добавить через код.
так же стоит вопрос по поводу размера файла.
без сжатия разные варианты сферы весят 1-2гб,в разных вьюверах файл больше 2 гб уже не открывался, вроде бы еще можно сжать этот файл тоже через код.
Мне нужно следить за весом файла и самостоятельно его сжимать или нет? (на видосе заметно, что качество отличается)
Еще углы поменяла, так устроит или нужно по-другому сделать?

**Comment by TorinAsakura** [comment]
> trim.04D6F0D3-EE7C-48D8-9E5E-15EEDFB5AE9E.MOV 
> 
> добавила источники света, их снова не получается экспортировать в формат gltf. вообще лампочек всего 3 и их можно добавить через код. так же стоит вопрос по поводу размера файла. без сжатия разные варианты сферы весят 1-2гб,в разных вьюверах файл больше 2 гб уже не открывался, вроде бы еще можно сжать этот файл тоже через код. Мне нужно следить за весом файла и самостоятельно его сжимать или нет? (на видосе заметно, что качество отличается) Еще углы поменяла, так устроит или нужно по-другому сделать?

Да, уже близко. Поработай над стартовой позицией и выходом, они отличаются от оригинала, это относится также к скорости морфа.

Насчёт размеров - следуй рекомендациям. Могу точно сказать, что нам нужны будут шейдеры.

**Comment by pussypistolss** [comment]
Сделала как-то так

https://github.com/torin-asakura/dream-team/assets/147274591/c5bbd09e-473f-4e36-b216-ee5dbd363519



А в смысле шейдеры нужны будут? Этот gltf шейдеры не поддерживает, ни свет, ни шейдерную анимацию через ноды.
Анимацию через модификаторы я могу с костылями с помощью аддона в этот формат запихать, а с шейдерами что делать?
Ты имеешь ввиду их работу через код прописать?

**Comment by TorinAsakura** [comment]
> Сделала как-то так. Справа без света, слева со светом
> 
>  IMG_7116.MP4 
> 
> А в смысле шейдеры нужны будут? Этот gltf шейдеры не поддерживает, ни свет, ни шейдерную анимацию через ноды. Анимацию через модификаторы я могу с костылями с помощью аддона в этот формат запихать, а с шейдерами что делать? Ты имеешь ввиду их работу через код прописать?

Разумеется, я же тебе про threejs не просто так писал, без шейдеров там делать вообще нечего, мы не сможем ими управлять, а просто вставить файлик в код - это бестолковая затея.

**Comment by pussypistolss** [comment]
> > Сделала как-то так. Справа без света, слева со светом
> > IMG_7116.MP4
> > А в смысле шейдеры нужны будут? Этот gltf шейдеры не поддерживает, ни свет, ни шейдерную анимацию через ноды. Анимацию через модификаторы я могу с костылями с помощью аддона в этот формат запихать, а с шейдерами что делать? Ты имеешь ввиду их работу через код прописать?
> 
> Разумеется, я же тебе про threejs не просто так писал, без шейдеров там делать вообще нечего, мы не сможем ими управлять, а просто вставить файлик в код - это бестолковая затея.

А что по сфере думаешь? Устраивает или еще с ней поработать?

**Comment by TorinAsakura** [comment]
> > > Сделала как-то так. Справа без света, слева со светом
> > > IMG_7116.MP4
> > > А в смысле шейдеры нужны будут? Этот gltf шейдеры не поддерживает, ни свет, ни шейдерную анимацию через ноды. Анимацию через модификаторы я могу с костылями с помощью аддона в этот формат запихать, а с шейдерами что делать? Ты имеешь ввиду их работу через код прописать?
> > 
> > 
> > Разумеется, я же тебе про threejs не просто так писал, без шейдеров там делать вообще нечего, мы не сможем ими управлять, а просто вставить файлик в код - это бестолковая затея.
> 
> А что по сфере думаешь? Устраивает или еще с ней поработать?

Да, сфера в порядке, молодец. Теперь надо решить основную задачку - как всю эту красоту сделать доступной в коде

**Comment by Amiditin** [comment]
@pussypistolss по сфере, думаю, стоит попробовать сжать её размер, для более быстрой её загрузки. Также в [gltf preview](https://gltf-viewer.donmccurdy.com/) можно выставить параметры света и фона, мне нужны будут эти параметры, чтобы правильно настроить освещение в коде.

<details>

![image](https://github.com/torin-asakura/dream-team/assets/80476878/89048416-4393-40c9-8e12-489031297163)
</details>

**Comment by Amiditin** [comment]
@pussypistolss если есть возможность, можешь ещё добавить сферу в `.glb` формате.
