### ISSUE TITLE
Прелоадер

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/dream-team#48]
### Задача

Сделать прелоадер для https://dream-team.tech

### С чем связано?

Слишком долгая загрузка данных с вордпресса, в течение секунды сайт пустой и топорно подгружается прямо на глазах

### Материалы

https://user-images.githubusercontent.com/62806448/177160872-c3a1c987-3b4c-4a37-ae9f-b13abfc8631a.mov

### Как я это вижу

Один "большой" прелоадер который не пропадет, пока не подгрузятся все данные (как в фигме)

https://www.cobosrl.co/

**Comment by dakand** [comment]
@TFK70 насколько помню, с свг анимациями были проблемы, т.к. нужно подключать библиотеку для лотти. Поэтому я показал интерфейсную анимацию. 

![image](https://user-images.githubusercontent.com/75856342/179151849-c47c0656-4331-4b31-a8e9-d7c517e358b4.png)

Макеты можно воспринимать как кейфреймы анимации. Чтобы запустить анимацию нужно нажать на Present (красная рамка), без выделения какого-либо элемента на странице.

Я показал анимацию от начала и до полной загрузки сайта, поэтому к прелоадеру относятся не все экраны, а только условно выделенные (зелёная рамка).

В фиолетовой рамке параметры перехода.
