### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dream-team#95]
### С чем связан запрос на фичу?

Чуть меньше суток назад наши сайты были атакованы спам-рассылкой которая длилась почти 20 часов 

### Расскажите как вы это себе видите

Я завёл для сайта Dream Team reCaptcha у Google и добавил проверку рекаптчи в форму.
Тебе надо ожидать прохождение каптчи перед отправкой формы.

**Comment by carminio** [comment]
@TorinAsakura 

### Дебаг
При [выборе](https://github.com/torin-asakura/dream-team/blob/master/ui/form/src/form.component.tsx#L195) `size='invisible'`

Появляется такая ошибка: 
**This site key is not enabled for the invisible captcha.**

Нашёл вот это [link](https://github.com/magento/security-package/issues/25#issuecomment-517230353), посмотри, это включено?

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> ### Дебаг
> При [выборе](https://github.com/torin-asakura/dream-team/blob/master/ui/form/src/form.component.tsx#L195) `size='invisible'`
> 
> Появляется такая ошибка: **This site key is not enabled for the invisible captcha.**
> 
> Нашёл вот это [link](https://github.com/magento/security-package/issues/25#issuecomment-517230353), посмотри, это включено?

Проверяй

**Comment by TorinAsakura** [comment]
@carminio Оставь тогда пока. Потом покурю.
